name: ludivine publishing
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: setup nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run typecheck
      - run: npm run lint
      - run: npm run test
      - name: publish source
        uses: actions/upload-artifact@v3
        with:
          name: delivery
          path: |
            coverage/**
            src/**
            cli/**
            package.json
            package-lock.json
            LICENSE
          retention-days: 3
      - run: npm pack
      - name: publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: |
            **/*.tgz
          retention-days: 3
